### PR TITLE
Added support for argparse groups

### PR DESCRIPTION
**Pull request by fidelram**
Now sphinx-argparse understands the action groups encoded in argparse and properly formats the documentation. For an example, simply rebuild the html documentation. I updated the tests and the sample.py.

In the original code, to get the optional arguments a call to `parser._get_optional_actions()` was done. In the new version optional arguments are found from by iterating over parser._action_groups. I searched argparse itself prepares the documentation and the way they do it is by iterating over _action_groups.

### CODE REVIEW

**Comment by dpryan79** [comment]
@fidelram Can you check the "Allow edits from maintainers" box? I can resolve the merge conflicts then.

**Comment by dpryan79** [comment]
@fidelram: I think I've implemented this now in the `feature/groups` branch. Can you check if this implements what you want properly.

**Comment by fidelram** [comment]
@dpryan79 done ""Allow edits from maintainers"

**Comment by dpryan79** [comment]
I've merged the reimplementation.

**Pull request closed without merging**
